name: OQuaRE Evaluation

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run OQuaRE - Music
        uses: tecnomod-um/oquare-metrics@v3.0
        with:
          ontology-files: ontologies/music.ttl
          contents-folder: OQuaRE/music
          reasoner: HERMIT

      - name: Run OQuaRE - Pizza
        uses: tecnomod-um/oquare-metrics@v3.0
        with:
          ontology-files: ontologies/pizza.ttl
          contents-folder: OQuaRE/pizza
          reasoner: HERMIT